brain_two/urls.py
# from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from todos.views import (
    TodoListView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", TodoListView.as_view(), name="tod_list_list"),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
)

urlpatterns = [
    path("todos/", TodoListView.as_view(), name="todos_list_list")
]

todos/models.py
from django.conf import settings
from django.db import models


# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE)

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

from todos.models import TodoList

# Create your views here.


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

    def get_queryset(self):
        return TodoList.objects.all()

todos/templates/base.html
{% comment %} {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Lists</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
  </header>
</body>

</html> {% endcomment %}

todos/templates/todos/list.html
<!DOCTYPE html>
<html land="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <table>
                <thread>
                    <tr>
                        <th>Name</th>
                        <th>Number of Items</th>
                    </tr>
                </thread>
                <tbody>
                    {% for todo in todolist_list %}
                    <tr>
                        <td>{{todo.name}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>